In [6]:
import numpy as np 
import pandas as pd 
import os 
import cv2 
import gc 
from tqdm import tqdm

In [17]:
files = os.listdir("./input/face-detection-data/dataset/")
files

['aishwarya_rai',
 'angelina_jolie',
 'arnold_schwarzenegger',
 'bhuvan_bam',
 'brad_pitt',
 'Courteney_Cox',
 'David_Schwimmer',
 'dhoni',
 'hardik_pandya',
 'Jennifer_Aniston',
 'Jim_Parsons',
 'Johnny_Galeck',
 'Kunal_Nayya',
 'Lisa_Kudrow',
 'manoj_bajpayee',
 'Matthew_Perry',
 'Matt_LeBlanc',
 'messi',
 'mohamed_ali',
 'Pankaj_Tripathi',
 'pewdiepie',
 'random_person',
 'ROHIT_SHARMA',
 'ronaldo',
 'Sachin_Tendulka',
 'scarlett_johansson',
 'Simon_Helberg',
 'suresh_raina',
 'sylvester_stallone',
 'virat_kohli']

In [18]:
image_array = []

label_array = []

In [22]:
image_array=[]  # it's a list later i will convert it to array
label_array=[]
path="./input/face-detection-data/dataset/"
# loop through each sub-folder in train
for i in range(len(files)):
    # files in sub-folder
    file_sub=os.listdir(path+files[i])

    for k in tqdm(range(len(file_sub))):
        try:
            img=cv2.imread(path+files[i]+"/"+file_sub[k])
            img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
            img=cv2.resize(img,(96,96))
            image_array.append(img)
            label_array.append(i)
        except:
            pass

100%|██████████| 391/391 [00:01<00:00, 280.09it/s]


In [23]:
import gc
gc.collect()

512

In [26]:
image_array = np.array(image_array)/255.0
label_array = np.array(label_array)

In [27]:
print(image_array[0])

[[[0.45490196 0.38823529 0.38039216]
  [0.25490196 0.18823529 0.18039216]
  [0.38823529 0.33333333 0.32156863]
  ...
  [0.52941176 0.5254902  0.50980392]
  [0.27058824 0.28235294 0.2627451 ]
  [0.25098039 0.25098039 0.24705882]]

 [[0.52941176 0.45490196 0.43529412]
  [0.4        0.3254902  0.30588235]
  [0.45098039 0.37647059 0.36078431]
  ...
  [0.30588235 0.30588235 0.29803922]
  [0.30980392 0.31764706 0.31372549]
  [0.25098039 0.24705882 0.26666667]]

 [[0.44705882 0.36862745 0.34117647]
  [0.40784314 0.31764706 0.28627451]
  [0.47843137 0.38431373 0.36862745]
  ...
  [0.36862745 0.36078431 0.36470588]
  [0.29411765 0.29803922 0.30980392]
  [0.24313725 0.23921569 0.26666667]]

 ...

 [[0.01176471 0.01176471 0.01176471]
  [0.01176471 0.01176471 0.01176471]
  [0.00784314 0.00784314 0.00784314]
  ...
  [0.05490196 0.05098039 0.07058824]
  [0.04313725 0.03921569 0.05882353]
  [0.05098039 0.04705882 0.06666667]]

 [[0.01176471 0.01176471 0.01176471]
  [0.01176471 0.01176471 0.01176471]


In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(image_array,label_array,test_size=0.15)

In [30]:
from keras import layers,callbacks,utils, applications, optimizers
from keras.models import Sequential, Model, load_model

In [31]:
len(files)

30

In [34]:
import tensorflow as tf

In [36]:
model = Sequential()
pretrained_model = tf.keras.applications.EfficientNetB0(input_shape=(96,96,3),include_top=False, weights="imagenet")
model.add(pretrained_model)
#im stupid i forgot pooling layers
model.add(layers.GlobalAveragePooling2D())
model.add(layers.Dropout(0.3))
#add dense layers 
model.add(layers.Dense(1))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 efficientnetb0 (Functional)  (None, 3, 3, 1280)       4049571   
                                                                 
 global_average_pooling2d (G  (None, 1280)             0         
 lobalAveragePooling2D)                                          
                                                                 
 dropout_2 (Dropout)         (None, 1280)              0         
                                                                 
 dense_1 (Dense)             (None, 1)                 1281      
                                                                 
Total params: 4,050,852
Trainable params: 4,008,829
Non-trainable params: 42,023
_________________________________________________________________


In [37]:
model.compile(optimizer = "adam", loss="mean_squared_error",metrics=["mae"])

In [ ]:
checkpoint = "trained_model/model"